### ISSUE TITLE
Ansible 2.8.* support

### ISSUE THREAD

**Issue by sbaerlocher** [Uberspace/paternoster#41]
When I use patermost with Ansible 2.8.* I get the following error message
```
Traceback (most recent call last):
  File "/usr/local/bin/paternoster", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/paternoster/shebang.py", line 42, in main
    **config
  File "/usr/local/lib/python2.7/dist-packages/paternoster/paternoster.py", line 256, in auto
    status = self.execute()
  File "/usr/local/lib/python2.7/dist-packages/paternoster/paternoster.py", line 286, in execute
    status = self._runner.run(self._get_runner_variables(), self._parsed_args.verbose)
  File "/usr/local/lib/python2.7/dist-packages/paternoster/runners/ansiblerunner.py", line 193, in run
    status = self._get_playbook_executor(variables, verbosity).run()
  File "/usr/local/lib/python2.7/dist-packages/paternoster/runners/ansiblerunner.py", line 168, in _get_playbook_executor
    passwords={},
TypeError: __init__() got an unexpected keyword argument 'options'
```
Can support for Ansible 2.8.* be added?

**Comment by luto** [comment]
Ansible apparently changed the way options are handled in [`afdbb0d9d`](https://github.com/ansible/ansible/commit/afdbb0d9d5bebb91f632f0d4a1364de5393ba17a#diff-b54c875fc6bfd4d98dcc488f06a07beaL114), so this might need a little investigation.

**Comment by perryflynn** [comment]
Would be nice to have support for the current ansible version.

**Comment by luto** [comment]
There is currently no ETA on 2.8 support, since we're not using it yet in our product. I'm more than happy to look at and merge pull requests, in case @sbaerlocher (@itigoag) or @perryflynn would like to step up.

**Comment by luto** [comment]
@sbaerlocher @perryflynn there is a 2.8 branch now :tada: Since you expressed your interest, you please have a look, test it and report back to us? https://github.com/Uberspace/paternoster/pull/44

**Comment by brutus** [comment]
For anyone wanting to review: the relevant changes are in https://github.com/Uberspace/paternoster/pull/44/commits/5c5620e7e1f4c4312d92412cb531bf1cdb0dc3d0

**Comment by perryflynn** [comment]
Awesome! I've tried to do the modifications by myself last year, but didn't make it. Will test this next weekend. 👍
